### ISSUE TITLE
Review the db_text_search gem code and README

### ISSUE THREAD

**Issue by glebm** [thredded/thredded#174]
Please :+1: 
https://github.com/thredded/db_text_search

**Comment by TheDudeWithTheThing** [comment]
any plans to go even further with the adapter methods?  I noticed we've got a lot of spots with 

`connection.adapter_name =~ /postgres/i`

just to track them

`CaseInsensitiveEq .add_ci_text_column`
`CaseInsensitiveEq .column_case_sensitive?`
`LowerAdapter. add_index`

Seems like there should be 1 spot where the `adapter_name` is being checked

But having said that, you're a beast and cranked through this, are you on vacation or something?  NIce work!  I'm ok getting this out to try it out and worry about more adapter action later.

**Comment by jayroh** [comment]
I have no comments on the gem code because I know it's TIP TOP QUALITY.

Only comments I would have are with regards to some clarification of terms

Under [Case-Insensitive string matching](https://github.com/thredded/db_text_search#case-insensitive-string-matching)
> Add an index in a migration to an existing CI or CS column

I assume "CI" and "CS" are short for "case-insensitive" and "case-sensitive", respectively? Would it be a pain in the ass to just spell that out? If anything maybe something like ...

> Add an index in a migration to an existing CI (case-insensitive) or CS (case-sensitive) column

(I note this because my idiot brain looks at those and I automatically think "continuous integration" and "computer science")

* * *

Down below that - 

```ruby
DbTextSearch::CaseInsensitiveEq.new(User.confirmed, :username).find(%w(Alice Bob))
```

Is the `User.confirmed` part an AR scope we want to search *within*? Like ... "give me all the confirmed users that have either the usernames Alice or Bob"?

* * *

Last question - 

```ruby
DbTextSearch::FullTextSearch.add_index connection, :posts, :content
```

DUMB question - that takes care of all the pg gist, mysql fulltext index creation stuff? Damn that's great. I should look in the source right now but I'm tired and lazy

**Comment by glebm** [comment]
@jayroh Thanks, I've fixed these bits in the README. Feel free to improve it further.

> Is the User.confirmed part an AR scope we want to search within? Like ... "give me all the confirmed users that have either the usernames Alice or Bob"?

Yes, updated the readme.

> question - that takes care of all the pg gist, mysql fulltext index creation stuff? 

Yes, and this is what'll let us write one database-agnostic squashed migration once #173 is merged!
