### ISSUE TITLE
Emojis need to be copied over to parent app

### ISSUE THREAD

**Issue by jayroh** [thredded/thredded#189]
Otherwise the emoji part of html-pipeline references images that don't exist.

Example:
![](https://www.evernote.com/l/AUqGuCegHlhEAKY04uWCFEm_LYnfvOu1FPIB/image.png)

**Comment by jayroh** [comment]
After running rake task in parent app

![](https://www.evernote.com/l/AUoIOYBvm5BCo60pfO7Z11kB8dV_sbwSL5AB/image.png)

**Comment by glebm** [comment]
Is it possible to have the html-pipeline use regular Rails assets instead of copying the files to public? I prefer this approach since it doesn't bloat the app's git repository, and allows for updating the images (with fixed paths it's impossible to do consistenly with cache headers). The gemoji gem warns that this may slow down asset lookups considerably, but I haven't found it to be the case in practice on Ruby 2.x.

**Comment by glebm** [comment]
Merged for now, hopefully later on there will be a solution that allows for both.

**Comment by jayroh** [comment]
I hope so too. Looks like Gemoji suggests writing a helper? Might need to
look further into the adapter in html-pipeline

**Comment by jayroh** [comment]
And thank you Gleb 😀

**Comment by jayroh** [comment]
Fixed with pr #190
