### ISSUE TITLE
Rubocop pickiness in the code

### ISSUE THREAD

**Issue by timdiggins** [thredded/thredded#311]
Would you mind @glebm and @jayroh if we tuned rubocop a little bit. A lot of the conventions are great but a few really slow me down.

I like using double quotes as I rarely need to change from double quotes to single, but I often have to do the other way around (introducing interpolation, adding an apostrophe)). I find having to use single-quotes fairly annoying and actually see no value to the [string consistency rule](https://github.com/bbatsov/ruby-style-guide/#consistent-string-literals). 

I *think* this would be done with:

```
Style/StringLiterals:
  Enabled: false
```

If you're open to tuning, I'll suggest a few others as I code.

**Comment by jayroh** [comment]
I'm always down for tuning, especially from a democratic POV, but if we're
going to make a hard turn in any direction we should make the entire
project compliant in a single shift. By that I mean - if we're shifting
from single to double, I would prefer having one single commit that rips
the band-aid off (so to speak) so we can move forward with the new rule.

**Comment by timdiggins** [comment]
@jayroh my point was not to *change* some rubocop rules but to relax some. However if you think it's important to have consistent usages of quotes, then I think we might as well stick with what we've got. Do reopen if you think it's possible to relax.

**Comment by jayroh** [comment]
@timdiggins I think this one is good to be open for discussion.

@TheDudeWithTheThing @glebm 

If we flip that bit we could use rubocop to make the change for us automatically, so it'd be a relatively light lift.

**Comment by glebm** [comment]
I favor single quotes, because they indicate that a string is a simple string with no interpolation (and for strings that contain single quotes but no interpolation, `%q()` is better than `"` IMO). There is a lot of discussion on the subject in the RuboCop tracker, and this is currently the default in RuboCop.

RuboCop has an autocorrect flag, and there are RuboCop plugins for most IDEs/editors, including RubyMine. Just write the code the way you're used to, then run autocorrect before committing?

With regards to other settings, I'd prefer we stick with RuboCop defaults as much as it makes sense, as these defaults were born out of community discussion and analysis of a large number of ruby codebases.

**Comment by timdiggins** [comment]
I think we should close this @jayroh -- especially since `rubocop -a` (unknown to me heretofore) makes this all much less important.

**Comment by jayroh** [comment]
Alright Tim, that's fine :).
