### ISSUE TITLE
What are some recommended WSIWYG editors?

### ISSUE THREAD

**Issue by lawso017** [thredded/thredded#312]
Curious as to the use case for WSIWYG editors using the after/before_content view override. I was unable to get tinymce to work by activating it on the standard post_content textarea -- the in-browser required field validation didn't pick up the post_content field as having content. I didn't spend too much time troubleshooting because basecamp/trix worked pretty nicely.

With trix, I added a trix element:

```
%trix-editor(input="post_content")
````

to the after_content partial, and then styled the existing post_content as to be invisible but still accessible so that browser required validations will still work:

````
  ul.thredded--form-list {
    textarea#post_content {
      height: 0px;
      opacity: 0;
      position: absolute;
    }
   }
````

Seems like  a decent way to go but curious as to other suggestions.

**Comment by glebm** [comment]
Haven't used it myself, but Woofmark seems pretty popular and in active development: http://bevacqua.github.io/woofmark/.

**Comment by jayroh** [comment]
Like Gleb I haven't used many (almost any) of these but there are some pretty good options out there. Trix would be high up on that list, of course. Some others follow ... note that some of these are definitely leaning more towards enhancing markdown instead of full WYSIWYG:

* http://prosemirror.net/
* https://tibastral.github.io/markdownify/
* http://quilljs.com/
* http://epiceditor.com/

A LONG time ago I used this with thredded.com 👉 http://www.wymeditor.org/demo/ ... but it may be a little long in the tooth these days.

If I had to choose one these days I'd try out prosemirror, woofmark (thanks for that @glebm - hadn't heard of it before today 😄), or markdownify

**Comment by andreibondarev** [comment]
@lawso017 Were you able to get @mention functionality to work?
