### ISSUE TITLE
Autocompletion for mentions within post textarea

### ISSUE THREAD

**Issue by timdiggins** [thredded/thredded#325]
I would really like to have autocomplete for mentions within post textarea. Any idea whether the current mechanism we're using (in private topics) would extend to textareas easily? Seems like it _might_ be better to not roll our own here?

Some library options with a recent commit history:
- https://github.com/yuku-t/jquery-textcomplete (looks best at first glance for the posts)
- https://github.com/podio/jquery-mentions-input  (looks ok but somewhat undermaintained )
- https://github.com/ichord/At.js (has other dependencies, seems a bit heavyweight and maybe overfeatured)

NB: the usage is differnent in public topic post textarea and private topic members input: we want to allow multiple mentions in same posts (it's a way of highlighting and mentioning people), whereas we want to only have a person listed once in members

**Comment by jayroh** [comment]
This has been on the back-burner for me for a while but I would be so thrilled to see this.

Since we use jQuery anyway the first option you posted, @timdiggins, looks fantastic. For a plain vanilla dependency-less alternative there's https://bevacqua.github.io/horsey/ as well. The demos are pretty nice and the lib looks flexible.

That being said - the quickest to "done" would probably be jquery-textcomplete :)

**Comment by glebm** [comment]
> Any idea whether the current mechanism we're using (in private topics) would extend to textareas easily?

The current mechanism on the frontend is select2 and it doesn't really work for this.

**Comment by timdiggins** [comment]
Horsey looks great, but quite heavy (in terms of code) and also didn't want the hassle of working out a CommonJs loading mechanism (browserify-rails, sprockets-commonjs: all seem to have some baggage, and would probably mean ditching sprockets-es6 for a babelify plugin... could be hours of pain)

text-complete was fairly straightforward, and we are using jquery
