### ISSUE TITLE
Select2 dependency

### ISSUE THREAD

**Issue by waclock** [thredded/thredded#336]
Hello,

could you update thredded 0.6.1 to use Select2 4.0? I currently had to downgrade my select2 to version 3.5 in order to make everything work, however Select2 4.0 has many new features that may be quite useful.

Regards

**Comment by jayroh** [comment]
Hey @waclock. I just took a look into this to get the dependencies loosened up so that either 3.5 or 4.x could be used and it looks like 4.x made some pretty significant breaking changes. To wit: after upgrading locally I'm running into the following error - http://stackoverflow.com/questions/29919108/select2-initselection-error

I'll take a look at this a little bit more but am wondering if it's something you've run into and would be able to help move towards the right direction.

@glebm - thoughts on just bumping the version up to 4.x and leaving behind the older select2 3.x revs?

**Comment by kradydal** [comment]
Do you have any thoughts about updating `select2` up to 4.x? I have just installed the thredded engine and had to downgrade my version of `select2` to 3.5 and change my `_select2.css` file. It will be great if you could upgrade to 4.x version.

**Comment by waclock** [comment]
@jayroh I don't know why I didn't get notified when you posted. Regarding your question, I haven't bumped into anything similar to what you're mentioning. 

I believe if I'm not mistaken I forked thredded, upgraded to 4.0 and didn't have any problems.

**Comment by glebm** [comment]
PRs are welcome. There was a previous attempt at https://github.com/thredded/thredded/pull/337 but it didn't actually make it compatible.

**Comment by glebm** [comment]
Thredded no longer depends on select2 https://github.com/thredded/thredded/pull/597
