### ISSUE TITLE
Sporadic spec failure in travis ci

### ISSUE THREAD

**Issue by EllaNancyFay** [thredded/thredded#352]
**Failure**
```
1) Thredded::TopicView#states prepends a read state
     Failure/Error: expect(topic_view.states[0]).to eq :read
     
       expected: :read
            got: :unread
```

**Builds**
https://travis-ci.org/thredded/thredded/jobs/149263730

Also happened here, but was fixed by rebuild

https://travis-ci.org/red56/thredded/builds/149438017

**Comment by jayroh** [comment]
I've seen the test suite fail locally as well. I'm confident that there is
some state leaking across tests depending on the order they're run at that
time. I don't have it in front of me now but I'm pretty sure we're running
the suite in random order, so ... to fix this would be someone getting a
failure locally, re-running it against the rspec seed #, and determining
where the state leakage is

**Comment by timdiggins** [comment]
@jayroh @EllaNancyFay this one doesn't look like an ordering problem because if it was being run in a random order we'd be able to see (and then reproduce the error locally):

```
Randomized with seed 63715
```

however that's not output in the travis build https://travis-ci.org/thredded/thredded/jobs/149263730

**Comment by jayroh** [comment]
Is the order of the tests running held all in that one seed number?

I thought it saved the test order to disk and referred to it via the seed number ¯\\\_(ツ)\_/¯

**Comment by glebm** [comment]
@jayroh The seed number is the random number generator seed. The rest of the program is deterministic, so in a sense yes the order of the test is held in that one number (for a fixed codebase).

I've made them run at random as they weren't previously, but yeah this issue is something else (don't know what yet).

**Comment by glebm** [comment]
Got the database log of a failure here, if anyone wants to take a closer look!
https://travis-ci.org/thredded/thredded/jobs/151749083

**Comment by timdiggins** [comment]
@glebm @jayroh @EllaNancyFay 
I think that by creating and using `Topic#last_post_at` we've fixed this spec (and real) bug. 

If you want the full reasoning, read on:

if you image a test like the following:

```ruby
      topic = create(:topic, with_posts: 3)
      last_post = topic.posts.order_oldest_first.last

      expect(topic.last_post_at - last_post.created_at).to eq(0) # fine
      expect(topic.updated_at - last_post.created_at).to eq(0) # fails, see below
```

The failure is:

```
     Failure/Error: expect(topic.updated_at - last_post.created_at).to eq(0)
     
       expected: 0
            got: 0.11082
```

This errors every time on postgresql and sqlite3 with a gap of about `0.11` for `sqlite3` and and about `0.15` for `postgresql` (the difference is about the speed of the an single create posts execution). And it would error (with a `1.0` difference) about a third of the time on `mysql2` (due to the fact that rails timestamps have 0 length fractional part in mysql out of the box)


So then have a look at https://github.com/thredded/thredded/blob/master/app/models/concerns/thredded/user_topic_read_state_common.rb#L12

```ruby
# part of UserTopicReadStateCommon
    def read?
      postable.last_post_at.to_i <= read_at.to_i
    end
```
which used to be 
``` ruby
     postable.updated_at.to_i <= read_at.to_i
```

You can see that occasionally (randomly) the updated_at and read_at would be partitioned by `to_i` into different integral seconds for postgresql about every six time and for sqlite3 about 10 times. Mysql would do the partitioning about a third of the time.

But now we're using last_post_at, this **should** go away. However we no longer have any need for the `to_i` (in fact we never did, and it was just obscuring an underlying problem). I propose we remove them.  #410
