### ISSUE TITLE
remove default_scope from messageboard

### ISSUE THREAD

**Issue by timdiggins** [thredded/thredded#407]
We should remove the default_scope from messageboards and just add a scope `.open` or `.unclosed` to messageboards whenever we use them. the order should be handled now by #404 

_(the more I use default scopes the less I like them, as initially attractive as they are)_

**Comment by jayroh** [comment]
Agreed. Default scopes are way way more trouble than they are worth.

**Comment by glebm** [comment]
This may be a bit tricky, since the default scope also applies to `belongs_to`.

Perhaps soft deletion (aka "logical deletion") should not be a responsibility of Thredded, since there are many gems that can provide it independently, such as [paranoia](https://github.com/rubysherpas/paranoia).

How about we just remove the closed column entirely?
In the migration, we can just raise an error if there are any `closed: true` messageboards, leaving the decision of what to do with them up to the user.
