### ISSUE TITLE
Topics with last post

### ISSUE THREAD

**Issue by timdiggins** [thredded/thredded#413]
In the task-oriented thredded extension I'm working on, I show the body of the last post in the list views.

So instead of:

<img width="450" alt="main_board___thredded_demo" src="https://cloud.githubusercontent.com/assets/18395/18818343/adbb4658-836e-11e6-9a59-e9b811ffa211.png">

I have:

<img width="974" alt="main_board___thredded_demo" src="https://cloud.githubusercontent.com/assets/18395/18818341/9a94588a-836e-11e6-8467-fb67a9857ed5.png">

This does make it longer (but using css to limit the height of the displayed post and fade out what is not shown) but does give a better at-a-glance view of what is the latest thing there (maybe more useful for the posts when each topic represents a piece of work to do (task-orientation) rather than a communication.

However @jayroh @glebm @TheDudeWithTheThing I just wanted to see if this was relevant to Thredded core, or if you felt it was only a specialist need.

**Comment by jayroh** [comment]
I think it's a cool and compelling feature but this is the first time I've seen the need for something like it. I'm more apt to err on the side of having less code, so I would continue on the path of an extension/plugin for now and, in time if need be, it could be pulled into core.

Once you're happy with where it is, @timdiggins, I would suggest making sure it's in the core README so that people know it's there and available to be used.

**Comment by timdiggins** [comment]
makes sense @jayroh
