### ISSUE TITLE
New homepage

### ISSUE THREAD

**Issue by glebm** [thredded/thredded#449]
@timdiggins @jayroh What do you guys think about the new homepage look and copy? https://thredded.org/

**Comment by timdiggins** [comment]
👍  I love it. Much cleaner and the split between explanation and demo is much more understandable. 

At some point we should publish docs from the codebase and then that will be a fourth tab. That can wait till 1.0 though 😉

**Comment by jayroh** [comment]
I looooooooove it! LOVE IT

**Comment by TheDudeWithTheThing** [comment]
look at that!

**Comment by glebm** [comment]
Yay! 🎉 

> At some point we should publish docs from the codebase and then that will be a fourth tab. That can wait till 1.0 though 😉

The docs are published at http://www.rubydoc.info/gems/thredded, will need to remember to add a link before v1.0!

**Comment by DTrejo** [comment]
Another suggestion: that the homepage has a quick note from each of the maintainers about threaded. It could be why you made it, how you're using it, what you want other contributors to know, whatever.

Inspiration:   
"I'm working on threaded because I love OSS" - Maintainer1, title, company
"We didn't do any load testing... but threaded still loads instantly when the forum has one user with 500,000 posts!" - Maintainer2, title, company
"We didn't see a simple, fast forum that one could self-host. So we made thredded" - Maintainer3, title, company

[...]
