### ISSUE TITLE
onPageLoad callbacks may not always get called (?)

### ISSUE THREAD

**Issue by timdiggins** [thredded/thredded#464]
Some components are adding their PageLoad callbacks within a jquery callback. 

But this is (at least sometimes) happening after the PageLoad callbacks have been fired.

so maybe we need to check for this and fire them immediately if  

```javascript
if (onPageLoadFiredOnce && window.Thredded.DOMContentLoadedFired) {
  callbacks();
}
```

ref: https://github.com/thredded/thredded/commit/8e7e1d399a35006b03630ff18e484fd66620f9f9#commitcomment-19721263

I've possibly seen this happening in a branch, but it's all a bit async and non-deterministic

**Comment by timdiggins** [comment]
update: this is I thjink with tubolinks < 5, or without turbolinks

**Comment by timdiggins** [comment]
I'm not convinced about the place where I had the problem (maybe it's a page-reload problem with turbolinks somehow). but I'm still not convinced about the current code in on_page_load.es6

**Comment by glebm** [comment]
I was thinking that with no turbolinks, jQuery.turbolinks / Turbolinks Classic, we should not fire immediately because jQuery.ready always fires on window.load: https://github.com/rails/jquery-rails/blob/47d15123e27ca22f642b7befaeb152339f5d466a/vendor/assets/javascripts/jquery3.js#L3882

Since firing on `window.load` in this case is suboptimal, I'll rewrite it without using `jQuery.ready` and hopefully the issue you are seeing will disappear.
