### ISSUE TITLE
Unable to run Thredded after following all the steps

### ISSUE THREAD

**Issue by samirph** [thredded/thredded#492]
I have followed all the installation steps and all of them worked correctly until I accessed the path "/forum".
I keep getting the error "No route matches {:action=>"update", :controller=>"thredded/messageboards"} missing required keys: [:id]"

I'm using Rails 5.0.0.1, ruby 2.3.0 (I've tried 2.2.3 too) and  I'm using devise 4.2.0.

Here's a screenshot of the error I'm getting.

![thredded_issue](https://cloud.githubusercontent.com/assets/4563904/20563093/1e7c934c-b16e-11e6-94fe-b7df273e2077.png)

Thredded is using the correct Model and I have added to routes.rb  mount Thredded::Engine => '/forum' 

Is there anything I've missed?

**Comment by jayroh** [comment]
Did you restart the server?

What do you see when you run

```

bundle exec rake routes | grep forum

```

- - -

Joel Oliveira

https://joeloliveira.com

https://shubox.io

On Wed, Nov 23, 2016 at 8:18 AM samirph

<
mailto:samirph <notifications@github.com>
> wrote:

a, pre, code, a:link, body { word-wrap: break-word !important; }

I have followed all the installation steps and all of them worked correctly until I accessed the path "/forum".

I keep getting the error "No route matches {:action=>"update", :controller=>"thredded/messageboards"} missing required keys: [:id]"

I'm using Rails 5.0.0.1, ruby 2.3.0 (I've tried 2.2.3 too) and I'm using devise 4.2.0.

Here's a screenshot of the error I'm getting.

https://cloud.githubusercontent.com/assets/4563904/20563093/1e7c934c-b16e-11e6-94fe-b7df273e2077.png

Thredded is using the correct Model and I have added to routes.rb mount Thredded::Engine => '/forum'

Is there anything I've missed?

—

You are receiving this because you are subscribed to this thread.

Reply to this email directly,
https://github.com/thredded/thredded/issues/492
, or

**Comment by samirph** [comment]
I have restarted the server quite a few times.

This is what I see when I run  

rake routes | grep forum

![forum-routes](https://cloud.githubusercontent.com/assets/4563904/20571687/a4d969e4-b18f-11e6-9e0a-eb57ecc3a29c.png)

It shows only the route "/forum" and the routes devise created for my model UserForum.
The routes that belong to Thredded are all accessed directly, like this.

![all-routes](https://cloud.githubusercontent.com/assets/4563904/20571802/15222a4c-b190-11e6-8c81-e90736bf0c49.png)

And I don't really know if that's how it should be.

**Comment by jayroh** [comment]
That second screenshot should be in the context of the mounted thredded engine so that looks right ... even though it's hard to tell since the screenshot cuts off what is above it (I'm guessing).

That's a weird error considering it's pointing to this line: https://github.com/thredded/thredded/blob/master/app/views/thredded/shared/_breadcrumbs.html.erb#L2

@samirph could you post the contents of your routes file here?

**Comment by glebm** [comment]
@samirph Also, could you posts the contents of `config/initializers/thredded.rb` here?

**Comment by samirph** [comment]
routes.rb
```
Rails.application.routes.draw do

  mount Thredded::Engine => '/forum'
  devise_for :user_forum
#home
  root :to => "home#index"

  get "/go" => "home#go"
end
```
thredded.rb

```
# frozen_string_literal: true
# Thredded configuration

# ==> User Configuration
# The name of the class your app uses for your users.
# By default the engine will use 'User' but if you have another name
# for your user class - change it here.
Thredded.user_class = 'UserForum'

# User name column, used in @mention syntax and should be unique.
# This is the column used to search for users' names if/when someone is @ mentioned.
Thredded.user_name_column = :name

# User display name method, by default thredded uses the user_name_column defined above
# You may want to use :to_s or some more elaborate method
# Thredded.user_display_name_method = :to_s

# The path (or URL) you will use to link to your users' profiles.
# When linking to a user, Thredded will use this lambda to spit out
# the path or url to your user. This lambda is evaluated in the view context.
Thredded.user_path = lambda do |user|
  user_path = :"#{Thredded.user_class.name.underscore}_path"
  main_app.respond_to?(user_path) ? main_app.send(user_path, user) : "/users/#{user.to_param}"
end

# This method is used by Thredded controllers and views to fetch the currently signed-in user
Thredded.current_user_method = :"current_#{Thredded.user_class.name.underscore}"

# User avatar URL. rb-gravatar gem is used by default:
Thredded.avatar_url = ->(user) { Gravatar.src(user.email, 128, 'mm') }

# ==> Permissions Configuration
# By default, thredded uses a simple permission model, where all the users can post to all message boards,
# and admins and moderators are determined by a flag on the users table.

# The name of the moderator flag column on the users table.
Thredded.moderator_column = :admin
# The name of the admin flag column on the users table.
Thredded.admin_column = :admin

# Whether posts and topics pending moderation are visible to regular users.
Thredded.content_visible_while_pending_moderation = true

# Whether users that are following a topic are listed on topic page.
Thredded.show_topic_followers = false

# This model can be customized further by overriding a handful of methods on the User model.
# For more information, see app/models/thredded/user_extender.rb.

# ==> Ordering configuration

# How to calculate the position of messageboards in a list:
# :position            (default) set the position manually (new messageboards go to the bottom, by creation timestamp)
# :last_post_at_desc   most recent post first
# :topics_count_desc   most topics first
Thredded.messageboards_order = :position

# ==> Email Configuration
# Email "From:" field will use the following
# Thredded.email_from = 'no-reply@example.com'

# Emails going out will prefix the "Subject:" with the following string
# Thredded.email_outgoing_prefix = '[My Forum] '

# ==> View Configuration
# Set the layout for rendering the thredded views.
Thredded.layout = 'thredded/application'

# ==> Post Content Formatting
# Customize the way Thredded handles post formatting.

# Change the default html-pipeline filters used by thredded.
# E.g. to replace default emoji filter with your own:
# Thredded::ContentFormatter.after_markup_filters[
#   Thredded::ContentFormatter.after_markup_filters.index(HTML::Pipeline::EmojiFilter)] = MyEmojiFilter

# Change the HTML sanitization settings used by Thredded.
# See the Sanitize docs for more information on the underlying library: https://github.com/rgrove/sanitize/#readme
# E.g. to allow a custom element <custom-element>:
# Thredded::ContentFormatter.whitelist[:elements] += %w(custom-element)

# ==> User autocompletion (Private messages and @-mentions)
# Thredded.autocomplete_min_length = 2 lower to 1 if have 1-letter names -- increase if you want

# ==> Error Handling
# By default Thredded just renders a flash alert on errors such as Topic not found, or Login required.
# Below is an example of overriding the default behavior on LoginRequired:
#
# Rails.application.config.to_prepare do
#   Thredded::ApplicationController.module_eval do
#     rescue_from Thredded::Errors::LoginRequired do |exception|
#       @message = exception.message
#       render template: 'sessions/new', status: :forbidden
#     end
#   end
# end

# ==> View hooks
#
# Customize the UI before/after/replacing individual components.
# See the full list of view hooks and their arguments by running:
#
#     $ grep view_hooks -R --include '*.html.erb' "$(bundle show thredded)"
#
# Rails.application.config.to_prepare do
#   Thredded.view_hooks.post_form.content_text_area.config.before do |form:, **args|
#     # This is called in the Thredded view context, so all Thredded helpers and URLs are accessible here directly.
#     'hi'
#   end
# end
```

**Comment by glebm** [comment]
@samirph These all look OK to me. Perhaps double grep for the word `messageboard` in the rest of the codebase to verify that you're not overriding anything that might conflict with thredded? `Thredded::ApplicationController` inherits from your main_app `ApplicationController` so it's possible.

**Comment by samirph** [comment]
Right, I will be removing those gems one by one for now. If it doesn't work I'll try debugging it directly in `_breadcrumbs.html.erb`.

**Comment by jayroh** [comment]
At this point I think that's your best bet. Put a breakpoint in there with
pry

```
<% require 'pry'; binding.pry %>
```

and inspect the object, or objects, that are causing the problem.

**Comment by samirph** [comment]
Finally found the problem.

I don't know exactly how it works, but it turns out my `inflections.rb` file inside the folder `initializers` was making Rails misunderstand the path `messageboards_path`.  As it was shown in the screenshot, it was trying to access the update action instead of the index action. Rails was considering the index action as `messageboards_index_path` instead, so I just erased the contents inside `inflections.rb` and  re-added Thredded to my project.

Thanks for the help!

**Comment by jayroh** [comment]
Wow. That's a deep one.

Glad you found it, @samirph! No way in hell we would have known :)

- - -

Joel Oliveira

https://joeloliveira.com

https://shubox.io

On Mon, Nov 28, 2016 at 3:24 PM samirph

<
mailto:samirph <notifications@github.com>
> wrote:

a, pre, code, a:link, body { word-wrap: break-word !important; }

Finally found the problem.

I don't know exactly how it works, but it turns out my

inflections.rb

file inside the folder

initializers

was making Rails misunderstand the path

messageboards_path

. As it was shown in the screenshot, it was trying to access the update action instead of the index action. Rails was considering the index action as

messageboards_index_path

instead, so I just erased the contents inside

inflections.rb

and re-added Thredded to my project.

Thanks for the help!

—

You are receiving this because you commented.

Reply to this email directly,
https://github.com/thredded/thredded/issues/492#issuecomment-263383677
, or

**Comment by samirph** [comment]
As you all expected, it was a problem with my code, not the gem itself.
Still, I think using `url_for controller: :messageboards, action: :index`  instead of  using `messageboards_path` would've avoided that error. 
I'm not quite sure though since I haven't tested it.
