### ISSUE TITLE
Question: deleting message boards

### ISSUE THREAD

**Issue by cireficc** [thredded/thredded#509]
After looking at [the routes](https://github.com/thredded/thredded/blob/master/config/routes.rb#L48), the ability to *edit* a message board is there, but not to delete. It seems that if you were to create one accidentally, it would forever be looming in your forum with no way to get rid of it. I actually did that.

Is it because of the nested topics/posts relationship and cascading delete? What would it take to get message board delete functionality?

**Comment by jayroh** [comment]
Hey @cireficc! I think this particular omission isn't for any reason other than lack of need. I don't think anyone who's used the gem has needed it ... until now!

As for what it would take to get that into the app ... if you wanted to implement that feature I can assure you that we would be happy to work with you to get it into the project.

**Comment by cireficc** [comment]
@jayroh People really didn't have a need for it? Wow haha, that was one of the first things I noticed I needed! That and file attachments to posts :P I would be happy to work on the feature, but honestly it would probably take me a while given my work schedule (and also getting familiar with the thredded project as a whole).

Do you have some starting tips for me? I know I'd need to modify routes, probably a model or two, tests, probably some views to throw in a 'delete' button, etc.

**Comment by jayroh** [comment]
As weird as that may sound ... and yeah, it might be an obvious one ... I have a feeling many people dropped into a rails console and deleted the messageboard that way. I had made a rake task that did a lot of this work several years ago (it has since been jettisoned into the digital ether) when I had several hundred-thousand-post/topic large messageboards that needed to be wiped out. It did the job just fine and I had needed it literally twice in the 16 years this project has existed (in various forms).

So - as for starting tips.

This is pretty much a plain rails app so the usual suspects to check out would be:

* routes
* pundit policy to define WHO gets to delete a messageboard - probably admins/super-admins?
* `thredded/messageboards_controller`
* a feature spec that details the admin experience of deleting a messageboard - it could probably live adjacent to the spec that outlines creating one.
* some updates to the view and stylesheet(s) for people that have the authority to delete the messageboard

**Comment by glebm** [comment]
@cireficc Meanwhile, here is how you can destroy a messageboard from the command line:

```bash
$ rails runner "Thredded::Messageboard.friendly_find!('url-slug').destroy!"
```

**Comment by cireficc** [comment]
@jayroh I'll see if I can start on this when I get some free time then, thanks for the tips :)

@glebm Sweet, that is really good to know that it's easily-doable via the console. I thought I was going to have to open up PGAdmin and write some SQL!

**Comment by shelmire** [comment]
Here we are almost 3 years later, and I have the same issue. Obviously I can delete them from the backend; but what about my users?

**Comment by glebm** [comment]
@shelmire This is an open-source project. If you need it, send a PR or pay someone to do so.

**Comment by shelmire** [comment]
@glebm I have opened https://github.com/thredded/thredded/pull/826 . I'm new to open source contribution, so let me know if anything needs to change (also please feel free to tweak it yourself and @ me).

**Comment by shelmire** [comment]
Resolved by https://github.com/thredded/thredded/pull/826
