### ISSUE TITLE
User admin page becomes broken after thredded update

### ISSUE THREAD

**Issue by allaud** [thredded/thredded#549]
Found user admin page to be broken after upgrading thredded from 0.9 to 1.0. When I visit the page `http://localhost:3000/admin/user/1` I see the following error:

    ActionController::UrlGenerationError in RailsAdmin::Main#show
    No route matches {:action=>"show", :controller=>"rails_admin/main", :id=>nil, :model_name=>"thredded~user_preference"}

**Comment by glebm** [comment]
That's a rails_admin URL, not a thredded one.
Did you copy and run the upgrade migration? https://github.com/thredded/thredded#upgrading-an-existing-install

**Comment by allaud** [comment]
@glebm this is true, but what I see from the error description: 

No route matches {
:action=>"show", 
:controller=>"rails_admin/main", 
:id=>nil, 
:model_name=>"thredded~user_preference"}

It seems like thredded is somehow redefining the default user model name

**Comment by glebm** [comment]
> It seems like thredded is somehow redefining the default user model name

Definitely not.

@allaud What's the full backtrace?

**Comment by allaud** [comment]
@glebm https://gist.github.com/allaud/14bf59bc9e979331cc080c345593db7a

**Comment by glebm** [comment]
@allaud This is a bug in rails_admin. Looks like rails_admin is trying to generate a URL for an association that has not been persisted [here](https://github.com/sferik/rails_admin/blob/ae2962ca9e2e/lib/rails_admin/config/fields/association.rb#L24).

`User.thredded_user_preference` is defined [here](https://github.com/thredded/thredded/blob/036a07b83bc8305b668d2f9adcf8c529bfa89c99/app/models/thredded/user_extender.rb#L56-L58). It has been defined like this since Thredded v0.3.0.

Rails Admin should be checking whether the record is `persisted?` before trying to generate a URL for it.

**Comment by allaud** [comment]
@glebm any ideas on how to make a quick'n'dirty fix?

**Comment by jayroh** [comment]
Is there a way for rails_admin to ignore certain objects? Or customize particular resource details? On the page that that's occurring on, don't show the section that's trying to load the association.

(If I recall correctly, this IS doable)

**Comment by jayroh** [comment]
This is not a helpful comment, by the way, BUT --- this is why rails_admin drives me mad. I can't remember for the life of me HOW to do something without diving into an hour's worth of digging through the docs to wrap my head around the DSL.

**Comment by ArisNance** [comment]
I'm currently having the same issue! Once I find a fix i'll post it.

**Comment by jayroh** [comment]
@ArisNance Previously, @glebm had mentioned that the problem is born here: https://github.com/sferik/rails_admin/blob/ae2962ca9e2e/lib/rails_admin/config/fields/association.rb#L24

If I were you I would drop `binding.pry` in there and play around with what `rails_admin` is trying to do. If there's something there that can be adjusted to work reliably w/thredded and the rest of your app then it may be time to either fork rails_admin for yourself or submit a patch upstream.
