### ISSUE TITLE
undefined method `entry_name'

### ISSUE THREAD

**Issue by hopewise** [thredded/thredded#654]
When I click on users at link: /forum/admin/moderation/users?locale=en

I get this error:

    undefined method `entry_name' for #<User::ActiveRecord_Relation:0x007fc38c0e9078>

Any idea?

**Comment by jayroh** [comment]
@hopewise I see no reference to a method or property of `entry_name` in the thredded codebase. Is this something in your parent layout or one of your views?

If you define an `entry_name` method on your `User` class this error should stop.

**Comment by hopewise** [comment]
in my application's codebase, there is no `entry_name ` either, here is what I get:

![screen shot 2017-11-19 at 9 23 15 am](https://user-images.githubusercontent.com/1061157/32988361-879ad550-cd0b-11e7-8957-7b1a67bcd0e7.png)

**Comment by subhransu** [comment]
Although this post is old and the issue is being closed - I thought it might be a good idea to post the fix that worked for me. This is not directly related to `thredded`. 

The issue seems to occur if you are using `will_paginate` and `will_paginate-bootstrap`. 

**thredded** uses `kaminari` for pagination and it seems there is a `page_entry_info` conflict between will_paginate and kaminari as mentioned in this thread: https://github.com/mislav/will_paginate/issues/254

I removed will_paginate from my Gemfile and did a `bundle install` again. The issue seems to have gone away. But if you want to keep both then you might need to find another work around.
