### ISSUE TITLE
moderation state validation error not handled

### ISSUE THREAD

**Issue by ericcf** [thredded/thredded#723]
To replicate: post a new topic, then open up two windows as a moderator and try to block in both windows. This raises ActiveRecord::RecordInvalid which is not handled. Should the exception be rescued and a friendly notification be displayed instead?

**Comment by timdiggins** [comment]
I think this ActiveRecord::RecordInvalid is a uniqueness criterion in the db which is currently not validated (and even if it was, might still appear due to race conditions)

1) Handle (`rescue_from`) RecordInvalid and display a generic page (wherever it occurs).
2) We could try to be super friendly and work out exactly what is happening in this specific action
3) We could add validations there (but wont' catch everything). 

If we were to rescue_from RecordInvalid at an app level, wondering what the best thing to do might be:

* Sorry, something went wrong, please [ go back ] (link or button to referer) and try again
* or, redirect to the referer and say "Sorry, something went wrong, please try again"
* If there's no referer, maybe just display the standard 500 page.

**Comment by glebm** [comment]
In this case it was an invalid record on `create!`. For most things, we have forms where we display the errors. I've now added some custom handling for this action.
