### ISSUE TITLE
Custom font size via sass being overridden 

### ISSUE THREAD

**Issue by leenyburger** [thredded/thredded#730]
In `/components/_messageboard.scss` `.thredded--messageboard--title` you are overriding the custom font size via sass variable used in `@extend %thredded--heading;` with `font-size: 1.125rem; // 18px`
This line should be removed so I can control the font via the sass variable.

**Comment by glebm** [comment]
It shouldn't be removed, because we want it to be larger than the base font size:

https://github.com/thredded/thredded/blob/9c4db86dfbfc37ef2df8530bc4392dc3e910d169/app/assets/stylesheets/thredded/base/_typography.scss#L1-L3

Let's introduce a new variable instead, e.g. `$thredded-messageboard-title-font-size`.

By the way, topic header font size is also hard-coded:

https://github.com/thredded/thredded/blob/9c4db86dfbfc37ef2df8530bc4392dc3e910d169/app/assets/stylesheets/thredded/components/_topic-header.scss#L11-L19

Here, we could introduce `$thredded-topic-header-font-size` and `$thredded-topic-header-font-size-tablet-and-up`.

PR welcome.

**Comment by leenyburger** [comment]
Great! Will try to get to it next week. Thanks for all your work, we're loving this gem.
