### ISSUE TITLE
Question: Why is email also sent to Thredded.email_from?

### ISSUE THREAD

**Issue by fastsyrup** [thredded/thredded#774]
Hi,

I was very surprised to see that for private messages a copy of the email is sent to Thredded.email_from. 

In the PrivateTopicMailer:
```
mail from: email_details.no_reply,
           to: email_details.no_reply,
           bcc: emails,
           subject: [
             Thredded.email_outgoing_prefix,
             t('thredded.emails.message_notification.subject',
               user: @post.user.thredded_display_name,
               topic_title: @post.postable.title)
           ].compact.join
```

What is the reason for this?

Cheers  and best regards

 - Mike

**Comment by glebm** [comment]
There needs to be at least one non-BCC recipient.

**Comment by timdiggins** [comment]
@glebm I reckon this ought to be highlighted in the docs (#776).

@fastsyrup It would be possible to send emails individually `to` each recipient rather than `bcc`-ing all . You could this in your app by creating a new  EmailNotifier class and configuring it  (This would be could be done in your main_app rather than in Thredded)

**Comment by glebm** [comment]
I would be open to adding a setting to send emails individually instead (`false` by default) but note that BCC is *much* more efficient. I usually just set up an email filter to ignore these.
