### ISSUE TITLE
Thredded Email does not send

### ISSUE THREAD

**Issue by createwithneets** [thredded/thredded#818]
Hi there,

Am wondering if there is a missing step in setting up the automatic emails for thredded? 

I did see the "Does not send email issue- https://github.com/thredded/thredded/issues/658" and made sure to check that the "Thredded.email_from" is defined in the initializer.

Unlike the user in the above issue, my log on both development and production is not indicating that anything has been sent. 

Roadie-Rails gem is installed as per instructions here: https://github.com/thredded/thredded/wiki/Styling-email-content 

And I use Sendgrid which is all set up already to send out receipts for customer purchases.

**Comment by timdiggins** [comment]
Hi @createwithneets sorry for the slow response on this. It's hard to help with a broad request like this. But to answer your question, there isn't an extra step in the most general case (we can be pretty sure of that, because of the number of people using and installing thredded following these instructions). 

Hopefully you found a fix. If not, and still need help,  feel free to open a new issue, hopefully with some details that will give us some kind of indication what it could be

**Comment by pickhardt** [comment]
Hey @createwithneets - did you figure out the issue? I am having a similar issue right now, where forum emails get triggered locally (and I confirmed with letter_opener and break points), and other emails send in production just fine, but emails from Thredded don't ever reach the email sending service.
