### ISSUE TITLE
Bug: The thredded gem conflicts with pure css

### ISSUE THREAD

**Issue by pickhardt** [thredded/thredded#833]
I made a simple app demonstrating this bug:
https://github.com/pickhardt/testapp

The bug is that the behavior of pure css grid (https://purecss.io/grids/) apparently breaks by just including the thredded gem. I don't even have to run the follow on instructions for this to occur.

More specifically, in the pure css grid framework, the following means "I want these three elements to show up in one row on desktop, but in three different rows on mobile" (as a common responsive design pattern)

```
<div class="pure-g">
  <div class="pure-u-1 pure-u-md-1-3">Part 1</div>
  <div class="pure-u-1 pure-u-md-1-3">Part 2</div>
  <div class="pure-u-1 pure-u-md-1-3">Part 3</div>
</div>
```

However, when you include thredded's gem, the divs always show up as one row, not three different rows as they're supposed to do on mobile or when the screen width is small.

Bug:

![bug](https://user-images.githubusercontent.com/610082/66696397-88680c00-ec80-11e9-8f20-2d673efe421e.png)

Working as intended:

![working-as-intended](https://user-images.githubusercontent.com/610082/66696398-88680c00-ec80-11e9-9c1a-5f4d337e80d7.png)

I've been investigating it tonight but have no idea where the bug is coming from. Maybe someone more familiar with thredded knows?

**Comment by pickhardt** [comment]
To recreate the bug, download the Rails app at https://github.com/pickhardt/testapp, comment out the thredded gem, and run it. Observe that resizing the browser window will make the "Part 1", "Part 2", and "Part 3" fall from one row on desktop to three rows as your browser window falls below the "medium" width (md stands for medium).

Then go to the Gemfile and toggle the thredded gem on
https://github.com/pickhardt/testapp/blob/master/Gemfile

Restart and run it again. You will see that the pure grid behavior no longer works when you reize the browser to "medium" or lower width. All you did was include the thredded gem though... you didn't change the css or include any thredded assets?

**Comment by timdiggins** [comment]
Very interesting. I did a few tests with this and it appears that it's not thredded per se that is causing the difference it's one of thredded's dependencies [autoprefixer-rails](https://github.com/ai/autoprefixer-rails).  Replace the requirement for thredded with simply autoprefixer-rails and you'll see the same issue.

The conflict occurs because the css in your repo uses prefixed forms of flex without specifying the standard one. 

Certainly if you add the standard forms after your prefixed forms the problem goes away:

after 

```
  display: -webkit-flex;
  -webkit-flex-flow: row wrap;

  display: -ms-flexbox;
  -ms-flex-flow: row wrap;

  -ms-align-content: flex-start;
  -webkit-align-content: flex-start;
```

add 

```
  display: flex;
  flex-flow: row wrap;
```

https://github.com/pickhardt/testapp/blob/master/app/assets/stylesheets/pure_grid.css.scss#L11-L18

Then it all works as expected. pure has just the standard forms in its current repo: https://github.com/pure-css/pure/blob/master/src/grids/css/grids-core.css#L28.  Not sure what it has in its distributed files.

see https://github.com/pickhardt/testapp/pull/1

**Comment by pickhardt** [comment]
Thanks, your fix works. How did you identify how to fix it?

I wonder if it's possible to remove the autoprefixer gem from thredded? You could just add browser vendor prefixes only to the thredded css.

**Comment by timdiggins** [comment]
I'm not an expert on autoprefixer but the reason you might want to use that is that it's a lot of churn otherwise to keep updating the project to be correct according to the latest specs. Also different sites (which include thredded) might want to support different browsers from the default (which they can do by adjusting the .browserslistrc configuration).

My understanding of the current specs is that flex should currently be used without vendor prefixing, or if using vendor prefixing for some browsers should at least have the un-prefixed version available.

https://drafts.csswg.org/css-flexbox-1/#conform-testing
https://developer.mozilla.org/en-US/docs/Web/CSS/flex#Browser_compatibility

Thus I *think* the css code you showed isn't in conformance with the current specs.

In terms of how I found the issue -- I just did got a page running in Chrome with and without thredded and then did some inspection of the properties of the two elements, and worked out the difference was to do with the application of flex on the parent element with `.pure-g` class. I looked at the concrete difference of the output css and it looked like a vendoring prefix difference. I guessed it was autoprefixer-rails at work.

You might be able to disable it by adding `AutoprefixerRails.uninstall(Rails.application.assets)` to an initializer but I haven't tried that.

I'm not sure what the impact of removing it from thredded's dependencies would be. Any thoughts @glebm 👋?

**Comment by glebm** [comment]
> Also different sites (which include thredded) might want to support different browsers from the default (which they can do by adjusting the .browserslistrc configuration).

Yes, exactly. We don't want to impose particular prefixes on a user, as they change all the time. Autoprefixer ensures that everyone, including people with little Rails experience, get sensible prefixes by default.

Not wanting autoprefixer is rare. You can easily disable it if that's what you really want.

PureCSS itself uses autoprefixer for building its `dist` files: https://github.com/pure-css/pure/blob/287e82a6bbd6c986ba2f4d49c67485d40950abf4/package.json#L15. You should consider using the source files for PureCSS instead (https://github.com/pure-css/pure/tree/master/src) so that all your CSS is prefixed using up-to-date and consistent autoprefixer settings.
