### ISSUE TITLE
Preview isn't previewing

### ISSUE THREAD

**Issue by dazzaroonie** [thredded/thredded#841]
Preview doesn't seem to preview the post:

![Screen Shot 2019-10-24 at 5 47 49 pm](https://user-images.githubusercontent.com/2475859/67460378-90fc1180-f686-11e9-811e-c520d601bcec.png)

Can anyone suggest why this might be happening?

**Comment by dazzaroonie** [comment]
I've loaded the console and nothing is being displayed.
I've loaded the Rails logs and nothing is out of the ordinary there either.
I'm using Webpack and I suppose Sprockets too and followed the instructions on your Code page.
I'm using whatever is shipped with Rails 6

**Comment by tomholford** [comment]
Experiencing the same issue, sharing in case this is helpful:

## console error message
![image](https://user-images.githubusercontent.com/16504501/77999667-0377c880-736e-11ea-9347-49f13a108eea.png)

## stack trace
![image](https://user-images.githubusercontent.com/16504501/77999882-581b4380-736e-11ea-9f5a-922bbdac951f.png)

**Comment by timdiggins** [comment]
@tomholford @dazzaroonie are you using  `turbolinks-render`? This is a library that enables "render" to work with Tubolinks remote-posted forms  (typically for server-side validation error rendering). However it's not part of the defaults for rails6. 

However, the default usage of it does interfere with how Thredded's preview works resulting in exactly the output you screenshotted @dazzaroonie.

I had exactly this problem and fixed them by using a specific branch of turbolinks-render (https://github.com/jorgemanrubia/turbolinks_render/pull/27) which allows you to then exclude paths. I then configured that in an initializer:

Gemfile:

```
gem 'turbolinks_render', github: "AndrewRadev/turbolinks_render", branch: "ignore-paths"
```

NB: for less fragility/more control you can use your own fork rather than using the AndrewRadev/turbolinks_render branch.


config/initializers/turbolinks.rb

```ruby
Rails.application.config.turbolinks_render.ignored_paths = [
  '/thredded'
]
```

**Comment by timdiggins** [comment]
Closing this as it's quite old now. Please reopen if you have more information.
