### ISSUE TITLE
Rails 6.1 Compatability

### ISSUE THREAD

**Issue by rickychilcott** [thredded/thredded#877]
I'm in the process of upgrading my app to Rails 6.1 and it appears that the views are broken because some of the rails view rendering has changed slightly.

Has anyone tried to get Rails 6.1 running?

**Comment by sudara** [comment]
I brute forced thredded for 6.1 and am running in production after clearing cache: https://github.com/sudara/thredded/commits/master

The issue seems to be the view caching stuff mainly related to method signatures changing.

I didn't open a PR as I didn't spent any time with the custom caching code to understand if any behavior had changed.

**Comment by rickychilcott** [comment]
Thanks @sudara. This will help me get the forum working again in my app and facilitate the 6.1 release of my app.

If I find the time, I'll see if I can try to get a 5.1 PR in.

**Comment by lemingos** [comment]
Have you tried with Ruby 3.0 ?

**Comment by rickychilcott** [comment]
Thanks @sudara. I was able to use parts of your fork to help, but it looks like maybe you weren't using master, so I had to make some small modifications and some work seems unnecessary.

@glebm can you check out #878 to see if it's helpful?

@lemingos I am on 2.7.2 right now and would like to get to 3.0 soon. I don't have any test coverage on Thredded in my app -- but I'm beginning to think I should have a few high level tests. Have you tried to get to 3.0 without success?
