### ISSUE TITLE
ruby-gravatar and GPL licensing

### ISSUE THREAD

**Issue by rickychilcott** [thredded/thredded#880]
In https://github.com/sn/ruby-gravatar/commit/5a1225c58f9363e66daae01698fcefc7d4f697b3, the author changed the license to GPL (from MIT). If you accidentally update all of your gems, you're likely to get the latest version which could jeopardize your business if Thredded is not used standalone and is used inside of another app.

I made an API-compatible gem (similar but different code) at https://github.com/mission-met/rails_gravatar and should more or less be a drop in. Bonus: I actually wrote tests for my gem and DON'T require using the `raw` tag helper around everything.

I can try to make a PR tomorrow or Sunday, if it will be accepted to this project but it might be faster for @glebm to just try out my gem, make the change, cut a new gem, and call it a day.

**Comment by rickychilcott** [comment]
Actually, it's not 100% API compatabile, but basically is. Steps to update:

1. Drop the `raw` tags
2. Change all `Gravatar.` to `RailsGravatar.`
3. Change `Gravatar.prefetch_dns` to `RailsGravatar.prefetch_dns_tag`

**Comment by timdiggins** [comment]
@rickychilcott the gem sounds cool, but I'm not sure about the risk statement ("GPL ... could jeopardize your business if Thredded is not used standalone and is used inside of another app"). Can you provide some reference that this is the case?

**Comment by glebm** [comment]
Your gem sounds like an improvement, please feel free to send a PR

**Comment by rickychilcott** [comment]
If you haven't recently followed the Rails/Mimemagic issue, https://emmanuelhayford.com/dislodging-mimemagic-and-understanding-mit-gnu-gpl/ appears to be a decent write up, Suez canal jokes aside.

Also, if you're now panicking that you too might have GPL dependencies in your codebase, check out https://github.com/github/licensed It might help you figure out semi-quickly.

I'll send a PR.

**Comment by rickychilcott** [comment]
Thanks @glebm!

**Comment by timdiggins** [comment]
PS @rickychilcott Thanks for the link  -- totally irrelevant of the PR and your great work on the railsgravatar gem and this gem, I just think we need to be really careful of the claims we're making around GPL  -- and avoid spreading panic.

I was peripherally aware of the mimemagic story but hadn't read that article, which was really great. The story of the mimemagic gem as I understand it from it is one of (unintentional) copyright infringement - GPL code was copied, modified and redistributed as part of the gem without the preserved copyright and license. However the article spells out that ["Rails Is Guilty Of No License Violation"](https://emmanuelhayford.com/dislodging-mimemagic-and-understanding-mit-gnu-gpl/#rails-is-guilty-of-no-license-violation), because... "Rails is not a derivative work of mimemagic" -- and gives an argument for why that is. You can go back and forth on what characterises a derivative work (derivative work is the legal terminology within copyright law, "covered work" is the terminology specific).  However in any case by creating a private (non-distributed) work using mimemagic, you wouldn't be propagating or conveying (in the GPL 3.0 senses) at all, or creating a "covered work". This only happens on distribution. It even specifically excludes the standard SaaS usage ("Mere interaction with a user through a computer network, with no transfer of a copy, is not conveying") . (NB this is true for GPL but not the  Affero GPL). 

Thanks again for your work on this, I just wanted to explain where I was coming from.

**Comment by rickychilcott** [comment]
Sounds good. I'm not a lawyer.

Do you regularly use GPL gems in your SaaS applications?
