### ISSUE TITLE
Bold Links are Completely Stripped from Email Notifications

### ISSUE THREAD

**Issue by Velora** [thredded/thredded#940]
**Expected behavior:** 

1. I write a post with a link that is made bold with markdown.
2. Followers receive a notification email containing all content from the post

**Actual behavior:** 

1. The notification email received completely removes links if they were bold in the original post. 

**Steps to Reproduce:**

1. Write a post containing the following: `**https://mysite.com**`
2. That text/html will be completely missing from the email received. 

Using v0.16.16

**Comment by timdiggins** [comment]
@Velora Thanks for the bug report! 

I've looked at this on a live site and as far as I can tell this bug occurs:

when you have the Onebox filter on (it's on by default - but I remove onebox in the site I manage -- e.g. amazon oneboxes are (I think) partially broken at present: https://meta.discourse.org/c/bug/1)

AND

you have markup around a raw URL which is not supported by onebox (ie. a generic link) .

In this case, the link is generated, but it has no content.

I think this is happening because when Thredded generates email post_notifications it sets `options[:onebox_placeholders]` to true in the local options which become the context of the html pipeline (this is normally not specified, so `nil`)

https://github.com/thredded/thredded/blob/b464f17b88a6e0cdbc0f6a29cfec6b4205dfc6f5/app/views/thredded/post_mailer/post_notification.html.erb#L11

In the OneboxFilter, when "onebox_placeholders" is set, this uses the specific Onebox::Preview.placeholder_html which seems to be empty, but it wraps it with some extra markup, so it doesn't appear to be empty to the caller so it treats it as if it was successfully oneboxed.

I'm working on a PR

**Comment by Velora** [comment]
@timdiggins awesome! I appreciate the explanation and quick fix!
