### ISSUE TITLE
problem generating routes within thredded if application helpers include url_helpers

### ISSUE THREAD

**Issue by saracarl** [thredded/thredded#960]
We've just installed thredded and are seeing an odd behaviour on URLs.  Every link from the forum site, with the exception of the devise/user ones, looks like this:  
`http://localhost:3000/forum/assets?action=index&controller=thredded%2Fmessageboards`
or
`http://localhost:3000/forum/assets?action=new&controller=thredded%2Fmessageboards` 
with `assets` inserted in the url instead of something more like the demo site's
`https://thredded.org/thredded/messageboards/new`

This is thredded-1.0.1, ruby 2.7.2, rails 6.0.3.2

The routes are configured:
```
Fromthepage::Application.routes.draw do
  # TODO make the URL fall under user and collection profile
  mount Thredded::Engine => '/forum'
```

```
                     new_messageboard GET      /messageboards/new(.:format)                                         thredded/messageboards#new
               show_messageboard_group GET      /messageboard-groups/:id(.:format)                                   thredded/messageboard_groups#show
                     edit_messageboard GET      /messageboards/:id/edit(.:format)                                    thredded/messageboards#edit
                          messageboard PATCH    /messageboards/:id(.:format)                                         thredded/messageboards#update
                                       PUT      /messageboards/:id(.:format)                                         thredded/messageboards#update
                                       DELETE   /messageboards/:id(.:format)                                         thredded/messageboards#destroy
         edit_messageboard_preferences GET      /:messageboard_id/preferences/edit(.:format)                         thredded/preferences#edit
....
```

You can see all of our changes here:  https://github.com/benwbrum/fromthepage/pull/3345/files

The only thing we changed in the initializer was `Thredded.user_name_column = :login`

Any suggestions?

**Comment by saracarl** [comment]
This seems similar to #686.

**Comment by timdiggins** [comment]
Thanks for reporting - the issue seems to be something unusual in your codebase. It's very helpful you included the link to your repo. 

Can you see if (temporarily) commenting the line `include Rails.application.routes.url_helpers` in export_helper.rb:2 (and then restarting your dev server) makes this problem go away?

**Comment by timdiggins** [comment]
Further discussion FYI / thinking aloud ...

I was inspired by the similar-ish problem in https://github.com/ankane/blazer/issues/191, and if we add include Rails.application.routes.url_helpers to the thredded dummy app then we get some similar routes-related problems in specs. 

However the solution used in that repo (https://github.com/ankane/blazer/commit/6048a2fdead7f361f1bd156334e7b7d2893d5346 - add `clear_helpers` to the engine's base Controller class -- ie. `Thredded::ApplicationController`) won't be possible as we explicitly will need to keep the mainapp's helpers in order to allow the application's own layout rather than the standalone layout.

I wonder if it is ever really necessary to add the `include Rails.application.routes.url_helpers` to a helper, given that the url_helpers are also added to the view context, but equally, I don't really understand why adding them to a helper will break the engine's internal routing.

**Comment by benwbrum** [comment]
Okay, @saracarl and I just tried commenting out all instances of `include Rails.application.routes.url_helpers` in our repo, and the urls are generating correctly.  Now we're off to figure out why we did all those includes, but this problem is fixed for us.  Thanks for all your help!

**Comment by timdiggins** [comment]
@benwbrum just to be clear it should only be the instances of `include Rails.application.routes.url_helpers` in helpers which cause this problem -- just adding that to a model shouldn't cause a problem (and the inclusion in a helper should be unnecessary, whereas the inclusion in a model is usually for a reason)

**Comment by timdiggins** [comment]
@benwbrum @saracarl There's a possible fix (if you want to keep your url_helpers lines) in #961 - if you try it out, can you report back if it fixes your issues?

**Comment by benwbrum** [comment]
I just tried #961 and it doesn't seem to fix our issues.  I will be exploring more to see if there's a difference between the `include` statements in our `lib` files vs. our helpers.

**Comment by benwbrum** [comment]
Okay, it looks like if I comment out the include statement in our `app/helpers/export_helper.rb` and use your #961 branch, paths are generated correctly.  That greatly reduces the amelioration we're going to need to do in our repo -- thanks!
